name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libsdl1.2-dev libsdl-gfx1.2-dev libz80ex-dev
      - name: Make
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          cmake --build .
