name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: 'apt-get update && apt-get install -y libsdl1.2-dev libsdl-gfx1.2-dev'
      - name: Make
        run: make
